/*
 * https://leetcode.com/problems/find-the-difference/#/description
 *
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 */

#include <iostream>
#include <string>
#include <queue>
using namespace std;

// solution 1
class Solution {
public:
  char findTheDifference(string s, string t) {
    char result = 0;

    for (char c : s) result ^= c;
    for (char c : t) result ^= c;

    return result;
  }
};


// test
int main() {
  Solution solution;

  cout << solution.findTheDifference("asdf", "fdsaw") << endl;

  return 0;
}


